language: node_js 
sudo: required
node_js:
  - "14"
  - node

install:
  # - yarn global add travis-ci-cloudfront-invalidation
  - yarn install

script:
  - yarn test
  - yarn install
  - CI=false yarn build

before_deploy:
  - echo "START beginning the deployment step"

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "zanastaticapp"
  local_dir: build
  # region: "ap-southeast-1"
  region: ap-southeast-1
  name: "zanacpt-frontend"
  skip_cleanup: true
  acl: public_read
  on: 
    branch: PROD
  after_deploy:
  # - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST

after_deploy:
  - echo "END deployment of the app went successful"
